const devImages = [
    "affenpinscher.jpg",
    "afghan-hound.jpg",
    "akita.jpg",
    "australian-terrier.jpg",
    "basenji.jpg",
    "basset-hound.jpg",
    "beagle.jpg",
    "bedlington-terrier.jpg",
    "bichon-frise.jpg",
    "border-collie.jpg",
    "border-terrier.jpg",
    "borzoi.jpg",
    "boxer.jpg",
    "briard.jpg",
    "cairn-terrier.jpg",
    "chihuahua.jpg",
    "cocker-spaniel.jpg",
    "dachshund.jpg",
    "dalmatian.jpg",
    "english-setter.jpg",
    "french-bulldog.jpg",
    "giant-schnauzer.jpg",
    "golden-retriever.jpg",
    "gordon-setter.jpg",
    "great-dane.jpg",
    "havanese.jpg",
    "ibizan-hound.jpg",
    "irish-setter.jpg",
    "irish-terrier.jpg",
    "irish-wolfhound.jpg",
    "italian-greyhound.jpg",
    "japanese-spitz.jpg",
    "keeshond.jpg",
    "komondor.jpg",
    "kuvasz.jpg",
    "lakeland-terrier.jpg",
    "maltese.jpg",
    "miniature-pinscher.jpg",
    "miniature-schnauzer.jpg",
    "newfoundland.jpg",
    "norfolk-terrier.jpg",
    "norwegian-buhund.jpg",
    "norwegian-elkhound.jpg",
    "norwich-terrier.jpg",
    "otterhound.jpg",
    "papillon.jpg",
    "pomeranian.jpg",
    "pug.jpg",
    "rhodesian-ridgeback.jpg",
    "rottweiler.jpg",
    "russel-terrier.jpg",
    "saluki.jpg",
    "samoyed.jpg",
    "schipperke.jpg",
    "scottish-deerhound.jpg",
    "scottish-terrier.jpg",
    "sealyham-terrier.jpg",
    "shetland-sheepdog.jpg",
    "silky-terrier.jpg",
    "sussex-spaniel.jpg",
    "tibetan-mastiff.jpg",
    "tibetan-terrier.jpg",
    "vizsla.jpg",
    "weimaraner.jpg",
    "welsh-terrier.jpg",
    "whippet.jpg",
    "yorkshire-terrier.jpg"
];

const devFacts = [
    "Dogs have an amazing sense of smell, up to 100,000 times better than humans.",
    "The fastest dog breed is the greyhound, which can run up to 72 km/h.",
    "Dogs sweat through their paws.",
    "A dog's nose print is unique, much like a human fingerprint.",
    "Dalmatians are born completely white and develop their spots later.",
    "Dogs can hear sounds four times farther away than humans.",
    "The smallest dog breed is the Chihuahua.",
    "Dogs dream just like humans.",
    "A dog can understand up to 250 words and gestures.",
    "The oldest recorded dog lived to be 29 years old.",
    "Dogs have three eyelids.",
    "A dog's nose is so sensitive it can detect diseases.",
    "Dogs can sense human emotions.",
    "The largest dog breed is the English Mastiff.",
    "Dogs have about 1,700 taste buds, while humans have 9,000.",
    "Dogs can see in the dark thanks to an extra layer in their eyes.",
    "A dog's heart beats between 60 and 140 times per minute.",
    "Dogs can learn to recognize over 1,000 words.",
    "The first dog in space was named Laika.",
    "Dogs have been human companions for over 15,000 years."
];

const devDescription = [
    { name: "affenpinscher", description: "The Affenpinscher is a small and playful breed of dog that was originally bred in Germany for hunting small game. They are intelligent, energetic, and affectionate, and make excellent companion dogs." },
    { name: "afghan hound", description: "The Afghan Hound is a large and elegant breed of dog that was originally bred in Afghanistan for hunting small game. They are intelligent, independent, and athletic, and make excellent companion dogs." },
    { name: "akita", description: "The Akita is a large, muscular dog breed that originated in Japan. They are known for their loyalty and courage." },
    { name: "australian terrier", description: "The Australian Terrier is a small breed of terrier that originated in Australia. It is a compact and lively breed, with a short, wiry coat. Its head is large and round, with small, erect ears. Its legs are short and strong, and its tail is usually docked. The Australian Terrier is an intelligent and loyal breed, and it makes an excellent family pet. It is an active breed, and it needs regular exercise and mental stimulation. It is loyal and affectionate, and it enjoys spending time with its family." },
    { name: "basenji", description: "The Basenji is a small and agile breed of dog that was originally bred in Africa for hunting small game. They are intelligent, independent, and alert, and make excellent companion dogs." },
    { name: "basset hound", description: "The Basset Hound is a small and playful breed of dog that was originally bred in France for hunting small game. They are intelligent, affectionate, and loyal, and make excellent companion dogs." },
    { name: "beagle", description: "The Beagle is a small to medium-sized dog breed that was originally bred for hunting. They are known for their cheerful dispositions and keen sense of smell." },
    { name: "bedlington terrier", description: "The Bedlington Terrier is a small and athletic breed of dog that was originally bred in England for hunting small game. They are intelligent, playful, and affectionate, and make excellent companion dogs." },
    { name: "bichon frise", description: "The Bichon Frise is a small and playful breed of dog that was originally bred in France as a companion dog. They are intelligent, affectionate, and loyal, and make excellent family pets." },
    { name: "border collie", description: "The Border Collie is a medium-sized breed of herding dog from the borders of England and Scotland. These dogs are medium in size, with a thick double coat of fur to protect them from the cold. They have an energetic and intelligent demeanor, with an instinct for herding and working. They are highly trainable and obedient, but require firm and consistent training to be obedient. They are loyal and devoted to their family, with an independent nature that makes them well suited for herding and guard work." },
    { name: "border terrier", description: "The Border Terrier is a small and energetic breed of dog that was originally bred in England for hunting small game. They are intelligent, playful, and affectionate, and make excellent companion dogs." },
    { name: "borzoi", description: "The Borzoi is a large and athletic breed of dog that was originally bred in Russia for hunting wolves and other large game. They are intelligent, independent, and graceful, and make excellent companion dogs." },
    { name: "boxer", description: "The Boxer is a large and muscular breed of dog that was originally bred in Germany for guarding and protecting property. They are intelligent, loyal, and protective, and make excellent guard dogs." },
    { name: "briard", description: "The Briard is a large, muscular breed with a long, shaggy coat that is typically black, tawny, or gray. It is known for its loyalty and protective instincts." },
    { name: "cairn terrier", description: "The Cairn Terrier is a small and energetic breed of dog that was originally bred in Scotland for hunting small game. They are intelligent, playful, and affectionate, and make excellent companion dogs." },
    { name: "chihuahua", description: "The Chihuahua is a small, energetic breed that is known for its intelligence, loyalty, and big personality. This breed is native to Mexico, where it was originally kept as a companion and lapdog." },
    { name: "cocker spaniel", description: "The Cocker Spaniel is a medium-sized breed of dog that was originally bred in England for flushing and retrieving game. They are intelligent, friendly, and eager to please, and make excellent hunting dogs." },
    { name: "dachshund", description: "The Dachshund is a small and playful breed of dog that was originally bred in Germany for hunting small game. They are intelligent, independent, and affectionate, and make excellent companion dogs." },
    { name: "dalmatian", description: "The Dalmatian is a medium-sized breed that originated in Croatia. They have a short, dense coat, and come in a variety of colors. They are an active and energetic breed, and need plenty of exercise and mental stimulation. They are loyal and devoted to their owners, and make good family companions." },
    { name: "english setter", description: "The English Setter is a large, gentle breed of gundog with a distinctive silky, wavy coat and a calm, intelligent disposition." },
    { name: "french bulldog", description: "The French Bulldog is a small and playful breed of dog that was originally bred in France as a companion dog. They are intelligent, affectionate, and loyal, and make excellent family pets." },
    { name: "giant schnauzer", description: "The Giant Schnauzer is a large breed of working dog that originated in Germany. It is a powerful and athletic breed, with a thick, wiry coat. Its head is large and round, with small, erect ears. Its legs are strong and muscular, and its tail is usually docked. The Giant Schnauzer is an intelligent and loyal breed, and it makes an excellent family pet. It is an active breed, and it needs plenty of exercise and mental stimulation. It is loyal and affectionate, and it enjoys spending time with its family." },
    { name: "golden retriever", description: "The Golden Retriever is a large and muscular breed of dog that was originally bred in Scotland for retrieving game. They are intelligent, friendly, and eager to please, and make excellent family pets." },
    { name: "gordon setter", description: "The Gordon Setter is a large and athletic breed of dog that was originally bred for hunting. They are intelligent, energetic, and eager to please, and make excellent companion dogs." },
    { name: "great dane", description: "The Great Dane is a large and powerful breed of dog that was originally bred in Germany for hunting large game. They are intelligent, loyal, and gentle, and make excellent companion dogs." },
    { name: "havanese", description: "The Havanese is a small and playful breed of dog that was originally bred in Cuba as a companion dog. They are intelligent, affectionate, and loyal, and make excellent family pets." },
    { name: "ibizan hound", description: "The Ibizan Hound is a medium-sized hunting dog from the Balearic Islands of Spain. They are active, friendly, and intelligent, and make great family pets. Ibizan Hounds have a short, glossy coat that is usually white with red or chestnut markings. They are active and require plenty of exercise and mental stimulation to stay healthy and happy." },
    { name: "irish setter", description: "The Irish Setter is a medium-sized breed of dog that was originally bred for hunting. They are friendly, energetic, and intelligent, and make excellent companion dogs." },
    { name: "irish terrier", description: "The Irish Terrier is a medium-sized, energetic breed that is known for its intelligence, courage, and loyalty. This breed is native to Ireland, where it was originally used to hunt small game and vermin." },
    { name: "irish wolfhound", description: "The Irish Wolfhound is a large and muscular breed of dog that was originally bred for hunting wolves. They are gentle, intelligent, and loyal, and make excellent family pets." },
    { name: "italian greyhound", description: "The Italian Greyhound is a small and slender breed of dog that was originally bred for hunting small game. They are gentle, intelligent, and affectionate, and make excellent companion dogs." },
    { name: "japanese spitz", description: "The Japanese Spitz is a small, active breed with a long, fluffy coat. They have a triangular head and medium-sized, dark eyes with a friendly expression that is often described as “smiling.” The Japanese Spitz is an intelligent, loyal breed that loves to be around its family and is known for its affectionate nature." },
    { name: "keeshond", description: "The Keeshond is a medium-sized breed of dog that was originally bred in the Netherlands for guarding and protecting property. They are intelligent, friendly, and playful, and make excellent companion dogs." },
    { name: "komondor", description: "The Komondor is a large, imposing breed that is known for its distinctive white, corded coat and its independent, protective nature. This breed is native to Hungary, where it was originally used to guard flocks of sheep and cattle." },
    { name: "kuvasz", description: "The Kuvasz is a large, muscular breed that was originally bred to protect livestock. It is intelligent and loyal, but can be reserved with strangers." },
    { name: "lakeland terrier", description: "The Lakeland Terrier is a small, agile terrier breed with a wiry, weather-resistant coat and a distinctive plumed tail." },
    { name: "maltese", description: "The Maltese is a small, elegant breed with a long, silky coat. They have a round head with a short muzzle and large, black eyes with a gentle expression. The Maltese is an affectionate, happy breed that loves to be around its family and is known for its gentle and playful nature." },
    { name: "miniature pinscher", description: "The Miniature Pinscher is a small breed of dog that originated in Germany. It is a compact and lively breed, with a short, smooth coat. Its head is large and round, with small, erect ears. Its legs are short and strong, and its tail is usually docked. The Miniature Pinscher is an intelligent and loyal breed, and it makes an excellent family pet. It is an active breed, and it needs regular exercise and mental stimulation. It is loyal and affectionate, and it enjoys being around its family." },
    { name: "miniature schnauzer", description: "The Miniature Schnauzer is a small breed that originated in Germany in the late 19th century. They have a double coat of wiry fur, and come in a variety of colors. They are an intelligent and active breed, and make good family companions. They are alert, and make good watchdogs, and are loyal and devoted to their owners." },
    { name: "newfoundland", description: "The Newfoundland is a large and muscular breed of dog that was originally bred for working on boats and in the water. They are gentle and intelligent, and make excellent family pets." },
    { name: "norfolk terrier", description: "The Norfolk Terrier is a small and energetic breed of dog that was originally bred in England for hunting small game. They are intelligent, playful, and affectionate, and make excellent companion dogs." },
    { name: "norwegian buhund", description: "The Norwegian Buhund is a medium-sized breed of dog that was originally bred in Norway for herding and guarding livestock. They are intelligent, friendly, and energetic, and make excellent working dogs." },
    { name: "norwegian elkhound", description: "The Norwegian Elkhound is an ancient breed of Spitz-type hunting and guard dog from Norway. They are strong and powerful, yet friendly and loyal. Norwegian Elkhounds have a thick, double coat with a long, profuse undercoat and a short, thick outer coat. They come in various colors, including black and grey. They are independent and intelligent, and make great family pets." },
    { name: "norwich terrier", description: "The Norwich Terrier is a small breed of dog that originated in England. It is a compact and lively breed, with a short, wiry coat. Its head is large and round, with small, erect ears. Its legs are short and strong, and its tail is usually docked. The Norwich Terrier is an intelligent and friendly breed, and it makes a great family pet. It is an active breed, and it needs regular exercise and mental stimulation. It is loyal and affectionate, and it enjoys being around its family." },
    { name: "otterhound", description: "The Otterhound is a large and athletic breed of dog that was originally bred in England for hunting otters. They are intelligent, playful, and affectionate, and make excellent companion dogs." },
    { name: "papillon", description: "The Papillon is a small toy breed that originated in France. It is an active and intelligent breed that is friendly and outgoing. The Papillon stands between 8-11 inches at the shoulder and has a long, silky coat that can come in various colors and patterns." },
    { name: "pomeranian", description: "The Pomeranian is a small and playful breed of dog that was originally bred in Germany as a companion dog. They are intelligent, affectionate, and loyal, and make excellent family pets." },
    { name: "pug", description: "The Pug is a small, playful breed that is known for its comical expression, charming personality, and loyalty. This breed is native to China, where it was originally kept as a companion and lapdog by the imperial court." },
    { name: "rhodesian ridgeback", description: "The Rhodesian Ridgeback is a large and athletic breed of dog that was originally bred in Zimbabwe for hunting large game. They are intelligent, independent, and loyal, and make excellent companion dogs." },
    { name: "rottweiler", description: "The Rottweiler is a large and powerful breed of dog that was originally bred in Germany for herding and guarding livestock. They are intelligent, loyal, and protective, and make excellent working dogs." },
    { name: "russel terrier", description: "" },
    { name: "saluki", description: "The Saluki is a graceful and elegant breed, originating in the Middle East. They are a sight hound, and have a long, sleek coat in a variety of colors. They are highly intelligent, and have an independent nature. They are a fast breed, and have a long stride, and can be used for racing and coursing. They are loyal and devoted to their family, and make good companions." },
    { name: "samoyed", description: "The Samoyed is a large and fluffy breed of dog that was originally bred in Siberia for herding and guarding livestock. They are intelligent, friendly, and playful, and make excellent family pets." },
    { name: "schipperke", description: "The Schipperke is a small breed of dog from Belgium. These dogs are small in size, with a thick double coat of fur. They have a lively and energetic demeanor, with an instinct for hunting and tracking. They are highly intelligent and trainable, but require firm and consistent training to be obedient. They are loyal and devoted to their family, but can be stubborn and independent at times." },
    { name: "scottish deerhound", description: "The Scottish Deerhound is a large breed of sighthound that originated in Scotland. It is a powerful and athletic breed, with a long, wiry coat. Its head is large and round, with small, erect ears. Its legs are strong and muscular, and its tail is usually docked. The Scottish Deerhound is an intelligent and loyal breed, and it makes an excellent family pet. It is an active breed, and it needs plenty of exercise and mental stimulation. It is loyal and affectionate, and it enjoys spending time with its family." },
    { name: "scottish terrier", description: "The Scottish Terrier is a small, sturdy breed with a wiry coat and a distinctive beard. It is known for its independent and intelligent nature." },
    { name: "sealyham terrier", description: "The Sealyham Terrier is a small and energetic breed of dog that was originally bred in Wales for hunting small game. They are intelligent, playful, and affectionate, and make excellent companion dogs." },
    { name: "shetland sheepdog", description: "The Shetland Sheepdog is a small, agile breed with a long, thick coat. They have a long head and a medium-sized muzzle, with bright, alert eyes and a lively expression. Shetland Sheepdogs are known for their intelligence, eagerness to please, and devoted loyalty to their owners. They make excellent family pets and are also used in agility, obedience, and herding events." },
    { name: "silky terrier", description: "The Silky Terrier is a small, sturdy terrier breed known for its soft, silky coat. They have a lively and alert personality, and are very loyal and affectionate towards their family. Silky Terriers are active and require regular exercise and mental stimulation to remain healthy and happy. They are intelligent and eager to please, and make great family pets." },
    { name: "sussex spaniel", description: "The Sussex Spaniel is a medium-sized breed of spaniel from the Sussex region of England. These dogs are medium in size, with a long and wavy coat of fur. They have a gentle and affectionate demeanor, making them excellent companion dogs. They are highly trainable and intelligent, with an instinct to retrieve game. They are loyal and devoted to their family, with an independent nature that makes them well suited for retrieving and guard work." },
    { name: "tibetan mastiff", description: "The Tibetan Mastiff is a powerful, muscular breed that is known for its courage, independence, and fierce loyalty. This breed is native to the Tibetan Plateau, where it was originally used to guard monasteries and protect flocks of sheep." },
    { name: "tibetan terrier", description: "The Tibetan Terrier is a small and playful breed of dog that was originally bred in Tibet as a companion dog. They are intelligent, affectionate, and loyal, and make excellent family pets." },
    { name: "vizsla", description: "The Vizsla is a medium-sized breed of dog that was originally bred in Hungary for hunting small game. They are intelligent, energetic, and determined, and make excellent hunting dogs." },
    { name: "weimaraner", description: "The Weimaraner is a large, powerful breed with a short, thick coat. They have a long, elegant head with a deep muzzle and a strong jaw. Weimaraners are an intelligent, active breed with a friendly, loyal nature and are often used in agility, obedience, and hunting events." },
    { name: "welsh terrier", description: "The Welsh Terrier is a small and energetic breed of dog that was originally bred in Wales for hunting small game. They are intelligent, playful, and affectionate, and make excellent companion dogs." },
    { name: "whippet", description: "The Whippet is a medium-sized dog breed with a slender, athletic build and a short, smooth coat that is typically blue, red, or fawn in color. They are known for their speed, grace, and agility, and were originally bred to hunt small game, such as rabbits, by sight." },
    { name: "yorkshire terrier", description: "The Yorkshire Terrier is a small, intelligent dog breed with a long, silky coat that is typically blue and tan in color. They are known for their feisty, independent nature and their affectionate personalities, and were originally bred to hunt rats and other vermin in the textile mills of Yorkshire, England." },
];

export { devImages, devFacts, devDescription };